[package]
name = "rb-okvs"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10"
bitvec = "1.0"
blake2 = "0.10"
sha256 = "1.4"
thiserror = "1.0"
